import './globals.css';

export const metadata = {
  title: 'Next App',
  description: 'Generated by next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
